#!/usr/bin/env python3
"""Build three 10h / 3-task data configs that vary ONLY the task mix.

Tasks (high inter-task variance): folding_boxes, folding_clothes, making_flowers.
Each config holds total data fixed at ~10h and varies how it is split:

    even        : 1/3  1/3  1/3      (boxes / clothes / flowers)
    50_25_25    : clothes 50%, boxes 25%, flowers 25%
    60_30_10    : clothes 60%, boxes 30%, flowers 10%

All three configs share ONE held-out eval set — 30 episodes per task (balanced,
90 total) — that is disjoint from every train set, so validation numbers are
comparable across the three mixes. A 1-episode-per-task viz set (3 eps) drives
train_viz.

Hours use task-specific mean episode length (frames/episodes ÷ 30 fps from
task_distribution_sql_v2.json); episode counts are chosen to hit the target
hours per task. Episodes are drawn from the hashes that are BOTH labelled for
the task (scores_by_task.json) AND staged in the zip volume (catalog.json),
shuffled once with a fixed seed; the eval set is carved off the front, train
sets off the remainder, so eval ∩ train = ∅.

Inputs (pull once from the robotics Modal env):
    modal volume get egoverse-training-outputs \\
        data_curation/per_task_v8_sharded_2026-05-20_01-33-48/scores_by_task.json scratch/sbt.json
    modal volume get mecka_data_zip catalog.json scratch/catalog.json

Run:
    python egomimic/scripts/mecka_process/build_3task_10h_configs.py \\
        --scores scratch/sbt.json --catalog scratch/catalog.json \\
        --sql logs/task_distribution_sql_v2.json
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = REPO_ROOT / "egomimic" / "hydra_configs" / "data"
EXTRA_DIR = DATA_DIR / "extra"

FPS = 30.0
SEED = 42
TOTAL_HOURS = 10.0
EVAL_EPS_PER_TASK = 30

BOXES, CLOTHES, FLOWERS = "folding_boxes", "folding_clothes", "making_flowers"
TASKS = [BOXES, CLOTHES, FLOWERS]

# (config name) -> {task: fraction of the 10h}
SPLITS = {
    "even": {BOXES: 1 / 3, CLOTHES: 1 / 3, FLOWERS: 1 / 3},
    "50_25_25": {CLOTHES: 0.50, BOXES: 0.25, FLOWERS: 0.25},
    "60_30_10": {CLOTHES: 0.60, BOXES: 0.30, FLOWERS: 0.10},
}


# --------------------------------------------------------------------------- #
def seconds_per_episode(sql_path: Path) -> dict[str, float]:
    sql = json.loads(sql_path.read_text())
    return {
        r["task"]: r["frames"] / r["episodes"] / FPS
        for r in sql["per_task"]
        if r.get("episodes")
    }


def staged_hashes_by_task(scores_path: Path, catalog_path: Path) -> dict[str, list[str]]:
    scores = json.loads(scores_path.read_text())
    catalog = json.loads(catalog_path.read_text())
    cat_hashes = {e["episode_hash"] for e in catalog}
    out = {}
    for t in TASKS:
        present = [h for h in scores.get(t, {}) if h in cat_hashes]
        out[t] = sorted(present)  # deterministic base order
    return out


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=0) + "\n")
    print(f"  wrote {path.relative_to(REPO_ROOT)}  ({len(data)} eps)")


# --------------------------------------------------------------------------- #
CONFIG_TEMPLATE = '''\
# 4×H200 — 3-TASK / ~10h, task-mix sweep point "{name}".
#
# Tasks: folding_boxes, folding_clothes, making_flowers (high inter-task
# variance). Total data fixed at ~{total_h:.0f}h; this point splits it
# {split_desc}.
# Generated by egomimic/scripts/mecka_process/build_3task_10h_configs.py (seed {seed}).
#
# Per-task episodes (≈hours):
{per_task_comment}
#   TRAIN total: {train_total} eps (~{train_hours:.2f}h)
#
# Shared held-out eval set (same across all three mix configs): {eval_total}
# episodes, {eval_per_task}/task, disjoint from every train set
# (mecka_3task_eval.json). train_viz: one episode per task (3 total).

_target_: egomimic.pl_utils.pl_data_utils.MultiDataModuleWrapper

use_tokenizer: true
model_name: "google/paligemma-3b-mix-224"
sampling_mode: random
annotation_key: annotations
default_prompt: ""

train_datasets:
  mecka_bimanual:
    _target_: egomimic.rldb.zarr.prefetch_dataset.PrefetchedMapDataset
    resolver:
      _target_: egomimic.rldb.zarr.prefetch_dataset.ZipEpisodeResolver
      zip_dir: /mnt/zarr-zip
      eps_to_use: egomimic/hydra_configs/data/extra/{train_json}
      valid_ratio: 0.0          # dedicated train list — eval is a separate held-out set
      debug: null
      min_frames: null
      key_map:
        _target_: egomimic.rldb.embodiment.human.Mecka.get_keymap
        mode: cartesian
        annotations: true
      transform_list:
        _target_: egomimic.rldb.embodiment.human.Mecka.get_transform_list
        mode: cartesian
    mode: train
    episodes_per_epoch: {train_total}     # == full train subset → stage-all before training
    epoch_frames: ${{multiply:${{trainer.limit_train_batches}},${{data.train_dataloader_params.mecka_bimanual.batch_size}}}}
    cache_dir: /cache/zarr_cache
    pool_size_gb: 100
    lookahead_epochs: 2.0
    n_copy_threads: 48
    prepare_timeout_s: 3600

valid_datasets:
  mecka_bimanual:
    _target_: egomimic.rldb.zarr.prefetch_dataset.PrefetchedMapDataset
    resolver:
      _target_: egomimic.rldb.zarr.prefetch_dataset.ZipEpisodeResolver
      zip_dir: /mnt/zarr-zip
      eps_to_use: egomimic/hydra_configs/data/extra/mecka_3task_eval.json
      valid_ratio: 1.0          # shared held-out eval — use ALL episodes
      debug: null
      min_frames: null
      key_map:
        _target_: egomimic.rldb.embodiment.human.Mecka.get_keymap
        mode: cartesian
        annotations: true
      transform_list:
        _target_: egomimic.rldb.embodiment.human.Mecka.get_transform_list
        mode: cartesian
    mode: valid
    episodes_per_epoch: {eval_total}      # full shared eval set ({eval_per_task}/task)
    cache_dir: /cache/zarr_cache_valid
    pool_size_gb: 25
    lookahead_epochs: 2.0
    n_copy_threads: 16
    prepare_timeout_s: 3600

train_viz_datasets:
  mecka_bimanual:
    _target_: egomimic.rldb.zarr.prefetch_dataset.PrefetchedMapDataset
    resolver:
      _target_: egomimic.rldb.zarr.prefetch_dataset.ZipEpisodeResolver
      zip_dir: /mnt/zarr-zip
      eps_to_use: egomimic/hydra_configs/data/extra/mecka_3task_viz.json
      valid_ratio: 1.0          # keep all viz episodes (no split)
      debug: null
      min_frames: null
      key_map:
        _target_: egomimic.rldb.embodiment.human.Mecka.get_keymap
        mode: cartesian
        annotations: true
      transform_list:
        _target_: egomimic.rldb.embodiment.human.Mecka.get_transform_list
        mode: cartesian
    mode: valid
    episodes_per_epoch: 3       # == n_tasks
    epoch_frames: 240           # 3 tasks × max_frames_per_episode=80
    max_frames_per_episode: 80
    cache_dir: /cache/zarr_cache_viz
    pool_size_gb: 5
    lookahead_epochs: 1.0
    n_copy_threads: 4
    prepare_timeout_s: 3600

train_dataloader_params:
  mecka_bimanual:
    batch_size: 64            # per-device; 4×H200 → 256 global batch
    num_workers: 16
    persistent_workers: false
    prefetch_factor: 6
    shuffle: true

valid_dataloader_params:
  mecka_bimanual:
    batch_size: 32
    num_workers: 4
    persistent_workers: false
    prefetch_factor: 2
    shuffle: false

train_viz_dataloader_params:
  mecka_bimanual:
    batch_size: 32
    num_workers: 1
    persistent_workers: false
    prefetch_factor: 2
    shuffle: false
'''


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--scores", default="scratch/sbt.json")
    ap.add_argument("--catalog", default="scratch/catalog.json")
    ap.add_argument("--sql", default="logs/task_distribution_sql_v2.json")
    ap.add_argument("--seed", type=int, default=SEED)
    args = ap.parse_args()

    spe = seconds_per_episode(Path(args.sql))
    by_task = staged_hashes_by_task(Path(args.scores), Path(args.catalog))

    rng = random.Random(args.seed)
    eval_pool: dict[str, list[str]] = {}
    train_pool: dict[str, list[str]] = {}
    for t in TASKS:
        hs = list(by_task[t])
        rng.shuffle(hs)
        if len(hs) < EVAL_EPS_PER_TASK + 1:
            raise SystemExit(f"{t}: only {len(hs)} staged eps — too few.")
        eval_pool[t] = sorted(hs[:EVAL_EPS_PER_TASK])
        train_pool[t] = hs[EVAL_EPS_PER_TASK:]  # keep shuffled order for prefix-taking

    print("Episode lists -> egomimic/hydra_configs/data/extra/")
    # shared eval + viz
    eval_all = sorted(h for t in TASKS for h in eval_pool[t])
    write_json(EXTRA_DIR / "mecka_3task_eval.json", eval_all)
    viz = sorted(eval_pool[t][0] for t in TASKS)  # one per task (drawn from eval)
    write_json(EXTRA_DIR / "mecka_3task_viz.json", viz)

    summary = {}
    for name, split in SPLITS.items():
        sel: dict[str, list[str]] = {}
        for t in TASKS:
            n = round(TOTAL_HOURS * split[t] * 3600 / spe[t])
            if n > len(train_pool[t]):
                raise SystemExit(
                    f"{name}/{t}: need {n} eps but only {len(train_pool[t])} available."
                )
            sel[t] = sorted(train_pool[t][:n])
        flat = sorted(h for t in TASKS for h in sel[t])
        train_json = f"mecka_3task_10h_{name}.json"
        write_json(EXTRA_DIR / train_json, flat)

        per_task_comment = "\n".join(
            f"#     {t:16s} {len(sel[t]):4d} eps  (~{len(sel[t]) * spe[t] / 3600:.2f}h)"
            for t in TASKS
        )
        split_desc = ", ".join(f"{t} {split[t] * 100:.0f}%" for t in TASKS)
        train_hours = sum(len(sel[t]) * spe[t] / 3600 for t in TASKS)
        cfg = CONFIG_TEMPLATE.format(
            name=name,
            total_h=TOTAL_HOURS,
            split_desc=split_desc,
            per_task_comment=per_task_comment,
            train_total=len(flat),
            train_hours=train_hours,
            eval_total=len(eval_all),
            eval_per_task=EVAL_EPS_PER_TASK,
            train_json=train_json,
            seed=args.seed,
        )
        cfg_path = DATA_DIR / f"mecka_zip_h200_3task_10h_{name}.yaml"
        cfg_path.write_text(cfg)
        print(f"  wrote {cfg_path.relative_to(REPO_ROOT)}")
        summary[name] = {t: (len(sel[t]), len(sel[t]) * spe[t] / 3600) for t in TASKS}

    print("\nPer-config train mix (episodes, hours):")
    for name, s in summary.items():
        tot_h = sum(h for _, h in s.values())
        parts = "  ".join(f"{t.split('_')[-1]}={n}({h:.2f}h)" for t, (n, h) in s.items())
        print(f"  {name:10s} {parts}   total={tot_h:.2f}h")
    print(f"\nShared eval: {len(eval_all)} eps ({EVAL_EPS_PER_TASK}/task), viz: {len(viz)} eps")


if __name__ == "__main__":
    main()
